<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>Q_speak</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization> -->

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <ApplicationIcon>Resources\Q-Speak.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Q-Speak.ico" />
    <Reference Include="SpVoice">
      <HintPath>Libs\SpVoice.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MouseKeyHook" Version="5.7.1" />
  </ItemGroup>
</Project>